backend/models/MscCollection.php
<?php

namespace backend\models;

use Yii;

class MscCollection extends \common\models\MscCollectionBase {

    public function rules()
    {
        return [
            [['collection_name'], 'required'],
            [['description'], 'string'],
            [['is_active', 'number_of_artists'], 'integer'],
            [['is_active', 'updated_at', 'created_at'], 'safe'],
            [['collection_name'], 'string', 'max' => 255],
            [['note', 'description'], 'string', 'max' => 500]
        ];
    }

}

common/models/SongBase.php
<?php

namespace common\models;

use common\helpers\Helpers;
use Yii;
use yii\behaviors\SluggableBehavior;
use backend\components\behaviors\UnicodeSluggableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

class SongBase extends \common\models\db\SongDB
{
    const STATUS_DELETE = -1;
    const STATUS_DRAFT = 0;
    const STATUS_APPROVED = 1;

    public function getMediaPathUrl() {
        if (strpos($this->media_path, 'http') === 0) {
            return $this->media_path;
        } elseif (strpos($this->media_path, '/cms_upload/') === 0) {
            return Yii::$app->params['media_url_cms']. $this->media_path;
        } elseif (strpos($this->media_path, '/usr_upload/') === 0) {
            return Yii::$app->params['media_url_user']. $this->media_path;
        } elseif (strpos($this->media_path, '/vcs_medias/') === 0) {
            return Yii::$app->params['media_url_vcs']. $this->media_path;
        } else {
            return Yii::$app->params['media_url']. $this->media_path;
        }
    }

    public function getAvatarUrl($w = null, $h = null) {
        if (!$w && !$h) {
            return Helpers::getMediaUrl($this->avatar);
        } else {
            return Helpers::getMediaUrl(Helpers::getThumbUrl($this->avatar, $w, $h));
        }

    }

    public function getThumbnailUrl($w = null, $h = null) {
        if (!$w && !$h) {
            return Helpers::getMediaUrl($this->thumbnail);
        } else {
            return Helpers::getMediaUrl(Helpers::getThumbUrl($this->thumbnail, $w, $h));
        }

    }

    public function getBannerUrl($w = null, $h = null) {
        if (!$w && !$h) {
            return Helpers::getMediaUrl($this->banner);
        } else {
            return Helpers::getMediaUrl(Helpers::getThumbUrl($this->banner, $w, $h));
        }

    }

    public function behaviors()
    {
        return [
            [
                'class' => UnicodeSluggableBehavior::className(),
                'attribute' => 'song_name',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    public function getAuthor()
    {
        return $this->hasOne(AuthorBase::className(), ['id' => 'author_id']);
    }

    public function getCountry()
    {
        return $this->hasOne(MscCountryBase::className(), ['country_code' => 'country_code']);
    }

    public function getArtists() {
        return $this->hasMany(ArtistBase::className(), ['id' => 'artist_id'])->viaTable('msc_song_artist', ['song_id' => 'id']);
    }

    public function getSongArtists() {
        return $this->hasMany(SongArtistBase::className(), ['song_id' => 'id']);
    }

    public function getCategory() {
        return $this->hasOne(MscCategoryBase::className(), ['id' => 'cate_id'])
            ->viaTable('msc_song_category', ['song_id' => 'id']);
    }
}

backend/controllers/MscCollectionController.php
<?php

namespace backend\controllers;

use backend\models\Album;
use backend\models\AlbumSearch;
use backend\models\MscCategory;
use backend\models\MscCategorySearch;
use backend\models\Playlist;
use backend\models\PlaylistSearch;
use Yii;
use backend\models\MscCollection;
use backend\models\MscCollectionSearch;
use yii\db\ActiveQuery;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Inflector;
use yii\helpers\StringHelper;
use common\components\slim\Slim;

/**
 * MscCollectionController implements the CRUD actions for MscCollection model.
 */
class MscCollectionController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all MscCollection models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MscCollectionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single MscCollection model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if (Yii::$app->request->isAjax) {
            $this->layout = false;
        }
        return $this->render('view', [
            'model' => $this->findModel($id),
            'isAjax' => Yii::$app->request->isAjax,
        ]);
    }

    /**
     * Creates a new MscCollection model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new MscCollection();
        $modelClassName =  Inflector::camel2words(StringHelper::basename($model::className()));

        $form_values = Yii::$app->request->post();
        // Lay du lieu anh upload len de validate
        // Neu ko co thi xoa
        $imageFieldName = 'image_path';
        $form_values[$imageFieldName] = Slim::getImagesFromSlimRequest($imageFieldName);
        if ($model->load($form_values) && $model->save()) {
            $images = Slim::getImages($imageFieldName);

            if($images != false && sizeof($images) > 0) {

                $imagePath = Slim::saveSlimImage('backend', Inflector::underscore(StringHelper::basename($model::className())), $images[0]);

                $model->$imageFieldName = $imagePath;
                $model->save();
            }

            Yii::$app->session->setFlash('info', Yii::t('backend', 'Thêm mới "{object}" thành công!', ['object' => Yii::t('backend', $modelClassName)]));

            // bo sung redirect
            if (Yii::$app->request->post('save_and_back')) {
                return $this->redirect(['index']);
            } elseif (Yii::$app->request->post('save_and_add')) {
                return $this->redirect(['create']);
            } else {
                return $this->redirect(['update', 'id' => $model->id]);
            }

        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }


    }

    /**
     * Updates an existing MscCollection model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelClassName =  Inflector::camel2words(StringHelper::basename($model::className()));

        $model->loadDefaultValues();
        $form_values = Yii::$app->request->post();

        // Lay du lieu anh upload len de validate
        $imageFieldName = 'image_path';
        $form_values[$imageFieldName] = Slim::getImagesFromSlimRequest($imageFieldName);

        if ($model->load($form_values) && $model->save()) {

            if ($form_values['change_'. $imageFieldName] == '1') {
                $oldImagePath = ($model->$imageFieldName)? Yii::getAlias('@backend_web'). DIRECTORY_SEPARATOR. $model->$imageFieldName: null;
                $images = Slim::getImages($imageFieldName);

                if($images != false && sizeof($images) > 0) {
                    $imagePath = Slim::saveSlimImage('backend', Inflector::underscore(StringHelper::basename($model::className())), $images[0]);
                    $oldAltPath = $model->$imageFieldName;

                    $model->$imageFieldName = $imagePath;
                    $model->save();

                    if ($oldAltPath != $imagePath) {
                        // Xoa file anh cu
                        if ($oldImagePath && file_exists($oldImagePath))
                            unlink($oldImagePath);

                    }
                } else {
                    $model->$imageFieldName = null;

                    $model->save();
                    // Xoa file anh cu
                    if ($oldImagePath && file_exists($oldImagePath))
                        unlink($oldImagePath);
                }
            }

            Yii::$app->session->setFlash('info', Yii::t('backend', 'Chỉnh sửa {object} thành công!', ['object' => Yii::t('backend', $modelClassName)]));

            // bo sung redirect
            if (Yii::$app->request->post('save_and_back')) {
                return $this->redirect(['index']);
            } elseif (Yii::$app->request->post('save_and_add')) {
                return $this->redirect(['create']);
            } else {
                return $this->redirect(['update', 'id' => $model->id]);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing MscCollection model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $modelClassName =  Inflector::camel2words(StringHelper::basename($model::className()));
        $model->is_active = MscCollection::STATUS_DELETE;
        $model->save();

        Yii::$app->session->setFlash('info', Yii::t('backend', 'Xóa {object} thành công!', ['object' => Yii::t('backend', $modelClassName)]));

        return $this->redirect(['index']);
    }

    /**
     * Finds the MscCollection model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MscCollection the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MscCollection::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


    public function actionAlbum($id)
    {
        $searchModel = new AlbumSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $model = $this->findModel($id);


        $albums = Album::find()
            ->alias('a')
            -> innerJoin('msc_collection_content c', '(c.content_id=a.id AND c.content_type = :type AND c.collection_id = :id)', [
                'type' => 'album',
                'id' => $id,
            ])
            //->orderBy('c.created_at DESC')
            ->all();

        return $this->render('album', [
            'model' => $model,
            'albums' => $albums,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionPlaylist($id)
    {
        $searchModel = new PlaylistSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $model = $this->findModel($id);


        $playlists = Playlist::find()
            ->alias('a')
            -> innerJoin('msc_collection_content c', '(c.content_id=a.id AND c.content_type = :type AND c.collection_id = :id)', [
                'type' => 'playlist',
                'id' => $id,
            ])
            //->orderBy('c.created_at DESC')
            ->all();

        return $this->render('playlist', [
            'model' => $model,
            'playlists' => $playlists,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCategory($id)
    {
        $searchModel = new MscCategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $model = $this->findModel($id);


        $list = MscCategory::find()
            ->alias('a')
            -> innerJoin('msc_collection_content c', '(c.content_id=a.id AND c.content_type = :type AND c.collection_id = :id)', [
                'type' => 'category',
                'id' => $id,
            ])
            //->orderBy('c.created_at DESC')
            ->all();

        return $this->render('category', [
            'model' => $model,
            'list' => $list,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
}

backend/views/msc-collection/album.php
<?php

use \yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

$this->title = $model->collection_name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Collection'), 'url' => ['msc-collection/index']];
$this->params['breadcrumbs'][] = $model->collection_name;
?>
    <div class="row album-index">
        <div class="col-md-12">
            <div class="portlet light portlet-fit portlet-datatable bordered">
                <div class="portlet-title">
                    <h3><?= Yii::t('backend', 'Collection') ?>: <?= $model->collection_name ?></h3>
                    <br/>
                    <div class="">
                        <?= Html::button(Yii::t('backend', 'Add album', [
                        ]),
                            [
                                'class' => 'btn btn-info btn-sm',
                                'data-target' => '#search-album-modal',
                                'data-toggle' => "modal"
                            ]) ?>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="table-container">
                        <?php
                        Pjax::begin(['formSelector' => 'form', 'enablePushState' => false, 'id' => 'mainGridPjax']);
                        ?>

                        <table class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th><?= Yii::t('backend', 'Country'); ?></th>
                                <th>
                                    <?= Yii::t('backend', 'Album name'); ?>
                                </th>
                                <th>
                                    <?= Yii::t('backend', 'Song num'); ?>
                                </th>
                                <th>
                                    <?= Yii::t('backend', 'Published time'); ?>
                                </th>
                                <th>
                                    <?= Yii::t('backend', 'Actions'); ?>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if (count($albums)): ?>
                                <?php foreach ($albums as $index => $content): ?>
                                    <tr id="album-<?= $content->id; ?>">
                                        <td>
                                            <?= ($content->country)? $content->country->country_name: null; ?>
                                        </td>
                                        <td><?= $content->album_name ?></td>
                                        <td>
                                            <?= number_format($content->number_of_songs); ?>
                                        </td>
                                        <td>
                                            <?= $content->published_time; ?>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-sm btn-danger btn-album-remove"
                                                    ahref="<?= \yii\helpers\Url::to([
                                                        'album/remove-to-collection',
                                                        'ctype' => 'collection',
                                                        'ctype_id' => $model->id,
                                                        'album_id' => $content->id,
                                            ]); ?>" album_id="<?= $content->id ?>"><?= Yii::t('backend', 'Remove') ?></button>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                            </tbody>
                        </table>


                        <?php
                        Pjax::end();
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div id="detail-modal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">

            </div>

        </div>
    </div>

    <!-- Modal -->
    <div id="search-album-modal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content">
                <?php echo $this->render('/album/_searchAjax', [
                    'model' => $searchModel,
                    'ctype' => 'collection',
                    'ctypeId' => $model->id,
                ]); ?>
                <?php
                Pjax::begin(['timeout' => 0, 'formSelector' => 'form#album-search-ajax', 'enablePushState' => false, 'id' => 'albumGridPjax']);
                ?>

                <?php Pjax::end(); ?>

                <div class="clearfix"></div>
            </div>

        </div>
    </div>
<?php
$this->registerJs(<<< EOT_JS_CODE
    $(document).ready(function() {
        $('#search-album-modal').on('click', '.btn-album-add', function() {
            var url = $(this).attr('ahref');
            var albumId = $(this).attr('album_id');

            $.get(url, function(resp) {

                if (resp.error_code == 0) {
                    $.pjax.reload({container:"#mainGridPjax",timeout:0})
                    toastr.info(resp.message);
                } else {

                }
            });
        });

        $('#mainGridPjax').on('click', '.btn-album-remove', function() {
            var url = $(this).attr('ahref');
            var albumId = $(this).attr('album_id');

            $.get(url, function(resp) {

                if (resp.error_code == 0) {
                    $.pjax.reload({container:"#mainGridPjax",timeout:0})
                    toastr.info(resp.message);
                } else {

                }
            });
        })
    });

EOT_JS_CODE
);
?>

backend/views/msc-collection/category.php
<?php

use \yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

$this->title = $model->collection_name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Collection'), 'url' => ['msc-collection/index']];
$this->params['breadcrumbs'][] = $model->collection_name;
?>
    <div class="row category-index">
        <div class="col-md-12">
            <div class="portlet light portlet-fit portlet-datatable bordered">
                <div class="portlet-title">
                    <h3><?= Yii::t('backend', 'Collection') ?>: <?= $model->collection_name ?></h3>
                    <br/>
                    <div class="">
                        <?= Html::button(Yii::t('backend', 'Add category', [
                        ]),
                            [
                                'class' => 'btn btn-info btn-sm',
                                'data-target' => '#search-category-modal',
                                'data-toggle' => "modal"
                            ]) ?>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="table-container">
                        <?php
                        Pjax::begin(['formSelector' => 'form', 'enablePushState' => false, 'id' => 'mainGridPjax']);
                        ?>

                        <table class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>
                                    <?= Yii::t('backend', 'Category name'); ?>
                                </th>
                                <th>
                                    <?= Yii::t('backend', 'Description'); ?>
                                </th>
                                <th>
                                    <?= Yii::t('backend', 'Created At'); ?>
                                </th>
                                <th>
                                    <?= Yii::t('backend', 'Actions'); ?>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if (count($list)): ?>
                                <?php foreach ($list as $index => $content): ?>
                                    <tr id="category-<?= $content->id; ?>">

                                        <td><?= $content->cate_name ?></td>
                                        <td>
                                            <?= ($content->description); ?>
                                        </td>
                                        <td>
                                            <?= $content->created_at; ?>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-sm btn-danger btn-category-remove"
                                                    ahref="<?= \yii\helpers\Url::to([
                                                        'msc-category/remove-to-collection',
                                                        'ctype' => 'collection',
                                                        'ctype_id' => $model->id,
                                                        'category_id' => $content->id,
                                            ]); ?>" category_id="<?= $content->id ?>"><?= Yii::t('backend', 'Remove') ?></button>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                            </tbody>
                        </table>


                        <?php
                        Pjax::end();
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div id="detail-modal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">

            </div>

        </div>
    </div>

    <!-- Modal -->
    <div id="search-category-modal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content">
                <?php echo $this->render('/msc-category/_searchAjax', [
                    'model' => $searchModel,
                    'ctype' => 'collection',
                    'ctypeId' => $model->id,
                ]); ?>
                <?php
                Pjax::begin(['timeout' => 0, 'formSelector' => 'form#category-search-ajax', 'enablePushState' => false, 'id' => 'categoryGridPjax']);
                ?>

                <?php Pjax::end(); ?>

                <div class="clearfix"></div>
            </div>

        </div>
    </div>
<?php
$this->registerJs(<<< EOT_JS_CODE
    $(document).ready(function() {
        $('#search-category-modal').on('click', '.btn-category-add', function() {
            var url = $(this).attr('ahref');
            var categoryId = $(this).attr('category_id');

            $.get(url, function(resp) {

                if (resp.error_code == 0) {
                    $.pjax.reload({container:"#mainGridPjax",timeout:0})
                    toastr.info(resp.message);
                } else {

                }
            });
        });

        $('#mainGridPjax').on('click', '.btn-category-remove', function() {
            var url = $(this).attr('ahref');
            var categoryId = $(this).attr('category_id');

            $.get(url, function(resp) {

                if (resp.error_code == 0) {
                    $.pjax.reload({container:"#mainGridPjax",timeout:0})
                    toastr.info(resp.message);
                } else {

                }
            });
        })
    });

EOT_JS_CODE
);
?>

backend/views/msc-collection/playlist.php
<?php

use \yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

$this->title = $model->collection_name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Collection'), 'url' => ['msc-collection/index']];
$this->params['breadcrumbs'][] = $model->collection_name;
?>
    <div class="row playlist-index">
        <div class="col-md-12">
            <div class="portlet light portlet-fit portlet-datatable bordered">
                <div class="portlet-title">
                    <h3><?= Yii::t('backend', 'Collection') ?>: <?= $model->collection_name ?></h3>
                    <br/>
                    <div class="">
                        <?= Html::button(Yii::t('backend', 'Add playlist', [
                        ]),
                            [
                                'class' => 'btn btn-info btn-sm',
                                'data-target' => '#search-playlist-modal',
                                'data-toggle' => "modal"
                            ]) ?>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="table-container">
                        <?php
                        Pjax::begin(['formSelector' => 'form', 'enablePushState' => false, 'id' => 'mainGridPjax']);
                        ?>

                        <table class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>
                                    <?= Yii::t('backend', 'Playlist name'); ?>
                                </th>
                                <th>
                                    <?= Yii::t('backend', 'Song num'); ?>
                                </th>
                                <th>
                                    <?= Yii::t('backend', 'Created At'); ?>
                                </th>
                                <th>
                                    <?= Yii::t('backend', 'Actions'); ?>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if (count($playlists)): ?>
                                <?php foreach ($playlists as $index => $content): ?>
                                    <tr id="playlist-<?= $content->id; ?>">

                                        <td><?= $content->playlist_name ?></td>
                                        <td>
                                            <?= number_format($content->number_of_songs); ?>
                                        </td>
                                        <td>
                                            <?= $content->created_at; ?>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-sm btn-danger btn-playlist-remove"
                                                    ahref="<?= \yii\helpers\Url::to([
                                                        'playlist/remove-to-collection',
                                                        'ctype' => 'collection',
                                                        'ctype_id' => $model->id,
                                                        'playlist_id' => $content->id,
                                            ]); ?>" playlist_id="<?= $content->id ?>"><?= Yii::t('backend', 'Remove') ?></button>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                            </tbody>
                        </table>


                        <?php
                        Pjax::end();
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div id="detail-modal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">

            </div>

        </div>
    </div>

    <!-- Modal -->
    <div id="search-playlist-modal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content">
                <?php echo $this->render('/playlist/_searchAjax', [
                    'model' => $searchModel,
                    'ctype' => 'collection',
                    'ctypeId' => $model->id,
                ]); ?>
                <?php
                Pjax::begin(['timeout' => 0, 'formSelector' => 'form#playlist-search-ajax', 'enablePushState' => false, 'id' => 'playlistGridPjax']);
                ?>

                <?php Pjax::end(); ?>

                <div class="clearfix"></div>
            </div>

        </div>
    </div>
<?php
$this->registerJs(<<< EOT_JS_CODE
    $(document).ready(function() {
        $('#search-playlist-modal').on('click', '.btn-playlist-add', function() {
            var url = $(this).attr('ahref');
            var playlistId = $(this).attr('playlist_id');

            $.get(url, function(resp) {

                if (resp.error_code == 0) {
                    $.pjax.reload({container:"#mainGridPjax",timeout:0})
                    toastr.info(resp.message);
                } else {

                }
            });
        });

        $('#mainGridPjax').on('click', '.btn-playlist-remove', function() {
            var url = $(this).attr('ahref');
            var playlistId = $(this).attr('playlist_id');

            $.get(url, function(resp) {

                if (resp.error_code == 0) {
                    $.pjax.reload({container:"#mainGridPjax",timeout:0})
                    toastr.info(resp.message);
                } else {

                }
            });
        })
    });

EOT_JS_CODE
);
?>